# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amulet < Formula
  desc ""
  homepage "https://github.com/jipilmuk/amulet"
  version "0.4.18"

  on_macos do
    url "https://github.com/jipilmuk/amulet/releases/download/v0.4.18/amulet_0.4.18_darwin_all.tar.gz"
    sha256 "4d0c4ce7109a31d1439239c0345d037171b5d2eb426136f6458c5ab7cb44e891"

    def install
      bin.install "amulet"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jipilmuk/amulet/releases/download/v0.4.18/amulet_0.4.18_linux_amd64.tar.gz"
      sha256 "d7bc9a16a84eb8e86a45a521241124e6ff16a1bf7872dc65ac3e0e0fbb740cf7"

      def install
        bin.install "amulet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jipilmuk/amulet/releases/download/v0.4.18/amulet_0.4.18_linux_arm64.tar.gz"
      sha256 "17454fc13979e7e181f3e37d0032397bd97ef263240d512e49d74818c264723f"

      def install
        bin.install "amulet"
      end
    end
  end
end
