# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class But < Formula
  desc ""
  homepage "https://github.com/hoehwa/but"
  version "0.2.5"

  on_macos do
    url "https://github.com/hoehwa/but/releases/download/v0.2.5/but_0.2.5_darwin_all.tar.gz"
    sha256 "fdedefe4efd441740d19725711925314914c6ec282fef1c98e74997fdf99025d"

    def install
      bin.install "but"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/but/releases/download/v0.2.5/but_0.2.5_linux_amd64.tar.gz"
      sha256 "7b796e05f285e257d5b24014aed15f8417322083456cab990b1c931f6644c5ac"

      def install
        bin.install "but"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/but/releases/download/v0.2.5/but_0.2.5_linux_arm64.tar.gz"
      sha256 "4687bf3db028ee02ac17acc366cc51c87d074710e6246ee7bc56367e0e758caf"

      def install
        bin.install "but"
      end
    end
  end
end
