# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliTemplateForHuman < Formula
  desc ""
  homepage "https://github.com/mindulle/cli-template-for-human"
  version "0.1.1"

  on_macos do
    url "https://github.com/mindulle/cli-template-for-human/releases/download/v0.1.1/cli-template-for-human_0.1.1_darwin_all.tar.gz"
    sha256 "e270f1f248ecfe876f3706649d83a8bc4cfec5a486593fc249d0fd9b07c8ab74"

    def install
      bin.install "cli-template-for-human"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mindulle/cli-template-for-human/releases/download/v0.1.1/cli-template-for-human_0.1.1_linux_arm64.tar.gz"
      sha256 "e76d7488b55c0db38aa69ba353b7851801773273669496f51263f21300adbea5"

      def install
        bin.install "cli-template-for-human"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mindulle/cli-template-for-human/releases/download/v0.1.1/cli-template-for-human_0.1.1_linux_amd64.tar.gz"
      sha256 "5fb15a8e46a6d9e3c463a72e557bfd6438929bc77c0dfb53876ca98baee525d2"

      def install
        bin.install "cli-template-for-human"
      end
    end
  end
end
