# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jongi < Formula
  desc ""
  homepage "https://github.com/hoehwa/jongi"
  version "0.1.7"

  on_macos do
    url "https://github.com/hoehwa/jongi/releases/download/v0.1.7/jongi_0.1.7_darwin_all.tar.gz"
    sha256 "4fa89397117921b7944289a61696302c286c595cf53d640052a15ba66f960044"

    def install
      bin.install "jongi"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/jongi/releases/download/v0.1.7/jongi_0.1.7_linux_amd64.tar.gz"
      sha256 "93d6cebb873852d3de90dec7908df290b3458cede9613028ae6fd57d6dea7045"

      def install
        bin.install "jongi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/jongi/releases/download/v0.1.7/jongi_0.1.7_linux_arm64.tar.gz"
      sha256 "070eb9c5c35c14f174c8f63e12259de4208d571477d21a82fb6d24651498e341"

      def install
        bin.install "jongi"
      end
    end
  end
end
