# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdexec < Formula
  desc ""
  homepage "https://github.com/hoehwa/mdexec"
  version "0.1.0"

  on_macos do
    url "https://github.com/mindulle/mdexec/releases/download/v0.1.0/mdexec_0.1.0_darwin_all.tar.gz"
    sha256 "3907b0a0d8c67eed3b40ca16a6215b6b6d7803e0e9b37d23e1857e9bdf7b9365"

    def install
      bin.install "mdexec"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mindulle/mdexec/releases/download/v0.1.0/mdexec_0.1.0_linux_arm64.tar.gz"
      sha256 "c705817bca9cec6d2ddc1a33891e99b37fd6208b4934f8e69bf955147bfefeae"

      def install
        bin.install "mdexec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mindulle/mdexec/releases/download/v0.1.0/mdexec_0.1.0_linux_amd64.tar.gz"
      sha256 "81ef3d7e7b242a099a85a2cb5b8ecf12aa035fefc27a282d3c6ab2886d707ded"

      def install
        bin.install "mdexec"
      end
    end
  end
end
