# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orb < Formula
  desc ""
  homepage "https://github.com/jipilmuk/orb"
  version "0.2.0"

  on_macos do
    url "https://github.com/jipilmuk/orb/releases/download/v0.2.0/orb_0.2.0_darwin_all.tar.gz"
    sha256 "3183ba7339df18748d8ff518d1c1bda6f183a81e0ba4b3773836602d3119f95c"

    def install
      bin.install "orb"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jipilmuk/orb/releases/download/v0.2.0/orb_0.2.0_linux_arm64.tar.gz"
      sha256 "78c1c4ffb33b227efe1c50bb32b72e457b9539b82351d5c1b23ead6645126115"

      def install
        bin.install "orb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jipilmuk/orb/releases/download/v0.2.0/orb_0.2.0_linux_amd64.tar.gz"
      sha256 "eec8a86cb6dace23c3c02f1f9ef20ea7bf72b44c50d440a6fcdf15ee6b164c4e"

      def install
        bin.install "orb"
      end
    end
  end
end
